import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Engine} from '../dist/engine.mjs';
const read=n=>JSON.parse(readFileSync(new URL('../dist/data/'+n+'.json',import.meta.url)));
const cards=read('cards'),rules=read('rules'),decks=read('decks');
function game(){const e=new Engine(cards,rules,{seed:42});e.start(['ST01','ST02'].map(n=>decks.find(d=>d.name.startsWith(n))));e.dispatch({type:'choose',value:'keep'});e.dispatch({type:'choose',value:'keep'});return e;}
function triggerFilm(e){const c=e.card('OP06-006',0,'field');c.joined=-1;e.s.players[0].turns=2;e.dispatch({type:'attach',uid:c.uid});e.dispatch({type:'attack',uid:c.uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',value:'finish'});if(e.s.prompt?.type==='lifeTrigger')e.dispatch({type:'choose',value:'no'});return c;}
test('ST13 Ace clears only face-up life at end turn before the opponent starts',()=>{const e=game();e.list(0,'leader')[0].id='ST13-002';const life=e.list(0,'life');life[0].faceUp=true;life[3].faceUp=true;e.dispatch({type:'endTurn'});assert.equal(e.list(0,'life').length,3);assert.equal(life[0].zone,'trash');assert.equal(life[3].zone,'trash');assert.equal(life[2].zone,'life');assert.equal(e.s.active,1);});
test('ST13 event rearranges life in chosen order while preserving face-up status and combat continuation',()=>{const e=game();e.s.active=1;e.s.players[1].turns=2;for(const d of e.list(0,'donReserve').slice(0,1))e.move(d,'don');const event=e.card('ST13-017',0,'hand'),leader=e.list(0,'leader')[0];e.list(0,'life')[1].faceUp=true;const before=e.s.players[0].life.slice(),faceUp=before[1];e.dispatch({type:'attack',uid:e.list(1,'leader')[0].uid,target:leader.uid});e.dispatch({type:'choose',uid:event.uid});e.dispatch({type:'choose',uids:[leader.uid]});assert.equal(e.s.prompt.type,'order');assert.equal(e.s.prompt.destination,'生命区');e.dispatch({type:'choose',uids:before.slice().reverse()});assert.deepEqual(e.s.players[0].life,before.slice().reverse());assert.ok(e.s.cards[faceUp].faceUp);assert.equal(e.s.prompt.type,'counter');e.dispatch({type:'choose',value:'finish'});assert.equal(e.list(0,'life').length,5);});
test('FILM delayed trash waits for end turn and survives its source leaving the field',()=>{const e=game(),source=triggerFilm(e);assert.equal(e.s.endings.length,1);const target=e.card('OP06-006',0,'field');e.move(source,'trash');e.dispatch({type:'endTurn'});assert.equal(e.s.active,0);assert.equal(e.s.prompt.type,'targets');assert.equal(e.s.prompt.min,1);assert.equal(e.s.prompt.cancelAllowed,false);e.dispatch({type:'choose',uids:[target.uid]});assert.equal(target.zone,'trash');assert.equal(e.s.active,1);assert.equal(e.s.endings.length,0);});
test('a queued effect is not removed by silencing its source; undo and reload preserve the pending obligation',()=>{let e=game();const source=triggerFilm(e);e.mod(source,'flag','Silence');const stored=JSON.parse(JSON.stringify({s:e.s,seed:e.seed,serial:e.serial}));e=new Engine(cards,rules);Object.assign(e,stored);e.dispatch({type:'endTurn'});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[source.uid]});assert.equal(e.s.active,1);e.undo();assert.equal(e.s.active,0);assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[source.uid]});assert.equal(e.s.endings.length,0);});
test('multiple pending end effects let the player choose their resolution order',()=>{const e=game(),source=triggerFilm(e);source.rested=false;e.dispatch({type:'attack',uid:source.uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',value:'finish'});if(e.s.prompt?.type==='lifeTrigger')e.dispatch({type:'choose',value:'no'});const second=e.card('OP06-006',0,'field');e.dispatch({type:'endTurn'});assert.equal(e.s.prompt.type,'endOrder');assert.equal(e.s.prompt.entries.length,2);e.dispatch({type:'choose',value:'1'});e.dispatch({type:'choose',uids:[source.uid]});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[second.uid]});assert.equal(e.s.active,1);assert.equal(e.s.endings.length,0);});
test('Black Maria returns exactly the current DON difference, including attached DON, at end turn',()=>{const e=game();for(const d of e.list(1,'donReserve').slice(0,2))e.move(d,'don');const source=e.card('OP08-074',0,'field');e.dispatch({type:'activate',uid:source.uid,index:0});e.dispatch({type:'choose',value:'2'});assert.equal(e.don(0).length,6);e.don(0)[0].attached=e.list(0,'leader')[0].uid;e.move(source,'trash');e.dispatch({type:'endTurn'});assert.equal(e.s.prompt.min,4);assert.equal(e.s.prompt.max,4);const selected=e.don(0).slice(0,4).map(x=>x.uid);e.dispatch({type:'choose',uids:selected});assert.equal(e.don(0).length,2);assert.ok(selected.every(u=>e.s.cards[u].zone==='donReserve'));assert.equal(e.s.active,1);});
test('Black Maria cannot use the gain effect while another Black Maria is present',()=>{const e=game(),source=e.card('OP08-074',0,'field');e.card('OP08-074',0,'field');e.dispatch({type:'activate',uid:source.uid,index:0});assert.equal(e.don(0).length,1);assert.equal(e.s.endings.length,0);assert.equal(e.s.prompt,null);});
test('Black Maria does not ask for negative or zero DON when behind the opponent',()=>{const e=game();for(const d of e.list(1,'donReserve').slice(0,8))e.move(d,'don');const source=e.card('OP08-074',0,'field');e.dispatch({type:'activate',uid:source.uid,index:0});e.dispatch({type:'choose',value:'0'});e.dispatch({type:'endTurn'});assert.equal(e.don(0).length,1);assert.equal(e.s.active,1);assert.equal(e.s.prompt,null);});
test('queued self activation does not affect a card that left and re-entered',()=>{const e=game(),leader=e.list(0,'leader')[0];leader.id=cards.find(x=>x.type==='领袖'&&rules[x.id].characterName==='Shirahoshi').id;e.list(0,'life')[0].faceUp=true;const source=e.card('OP11-107',0,'field');source.rested=true;e.dispatch({type:'activate',uid:source.uid,index:1});assert.equal(source.rested,true);e.move(source,'hand');e.move(source,'field',{rested:true});e.dispatch({type:'endTurn'});assert.equal(source.rested,true);assert.equal(e.s.active,1);});
