import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Engine} from '../dist/engine.mjs';
import {table} from '../dist/table.mjs';
const read=f=>JSON.parse(readFileSync(new URL('../dist/data/'+f,import.meta.url),'utf8'));
const cards=read('cards.json'),rules=read('rules.json'),decks=read('decks.json');
const starter=n=>decks.find(d=>d.name.startsWith(n));
function game(){const e=new Engine(cards,rules,{seed:42});e.start([starter('ST01'),starter('ST02')]);e.dispatch({type:'choose',value:'keep'});e.dispatch({type:'choose',value:'keep'});return e;}
function give(e,id,zone='hand',owner=0){const c=Object.values(e.s.cards).find(c=>c.id===id&&c.owner===owner);assert.ok(c,id);e.move(c,zone);return c;}
function dons(e,owner,n){for(const c of e.list(owner,'donReserve').slice(0,n-e.don(owner).length))e.move(c,'don');}
test('opening hands, life, first-turn draw and DON',()=>{const e=game();assert.equal(e.list(0,'hand').length,5);assert.equal(e.list(0,'life').length,5);assert.equal(e.list(0,'deck').length,40);assert.equal(e.don(0).length,1);e.dispatch({type:'endTurn'});assert.equal(e.s.active,1);assert.equal(e.list(1,'hand').length,6);assert.equal(e.don(1).length,2);e.assertState();});
test('illegal cost is atomic and cannot spend or deploy',()=>{const e=game(),c=give(e,'ST01-012');const before=structuredClone(e.s);assert.throws(()=>e.dispatch({type:'play',uid:c.uid}),/不足/);assert.deepEqual(e.s,before);});
test('DON attachment power applies only on its owner turn',()=>{const e=game(),l=e.list(0,'leader')[0];e.dispatch({type:'attach',uid:l.uid});assert.equal(e.power(l),6000);e.dispatch({type:'endTurn'});assert.equal(e.power(l),5000);});
test('first turn leader cannot attack even after attaching DON',()=>{const e=game();assert.equal(e.canAttack(e.list(0,'leader')[0],e.list(1,'leader')[0]),false);});
test('ordinary characters cannot attack the turn they enter',()=>{const e=game();e.s.players[0].turns=2;dons(e,0,3);const c=give(e,'ST01-003');e.dispatch({type:'play',uid:c.uid});assert.equal(e.canAttack(c,e.list(1,'leader')[0]),false);});
test('rush allows attack the entry turn after the first player turn',()=>{const e=game();e.s.players[0].turns=2;dons(e,0,5);const c=give(e,'ST01-012');e.dispatch({type:'play',uid:c.uid});assert.equal(e.canAttack(c,e.list(1,'leader')[0]),true);});
test('leader activated ability attaches rested DON and is once per turn',()=>{const e=game(),l=e.list(0,'leader')[0];e.don(0)[0].rested=true;e.dispatch({type:'activate',uid:l.uid,index:0});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[l.uid]});assert.equal(e.attached(l).length,1);assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}),/已使用/);});
test('blocker replaces target, rests, and lets defender counter',()=>{const e=game();e.s.players[0].turns=2;const blocker=give(e,'ST02-004','field',1),a=e.list(0,'leader')[0],d=e.list(1,'leader')[0];e.dispatch({type:'attack',uid:a.uid,target:d.uid});assert.equal(e.s.prompt.type,'block');e.dispatch({type:'choose',uids:[blocker.uid]});assert.equal(e.s.battle.target,blocker.uid);assert.ok(blocker.rested);assert.equal(e.s.prompt.type,'counter');});
test('equal power hits leader and removes one life; zero life alone does not lose',()=>{const e=game();e.s.players[0].turns=2;const a=e.list(0,'leader')[0],d=e.list(1,'leader')[0];e.dispatch({type:'attack',uid:a.uid,target:d.uid});e.dispatch({type:'choose',value:'finish'});if(e.s.prompt?.type==='lifeTrigger')e.dispatch({type:'choose',value:'no'});assert.equal(e.list(1,'life').length,4);assert.equal(e.s.winner,null);});
test('attack at zero life wins',()=>{const e=game();e.s.players[0].turns=2;for(const c of e.list(1,'life'))e.move(c,'hand');e.dispatch({type:'attack',uid:e.list(0,'leader')[0].uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',value:'finish'});assert.equal(e.s.winner,0);});
test('double attack with one remaining life does not win on the second damage',()=>{const e=game();e.s.players[0].turns=2;for(const c of e.list(1,'life').slice(1))e.move(c,'hand');const a=e.list(0,'leader')[0];e.mod(a,'flag','DoubleAttack');e.dispatch({type:'attack',uid:a.uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',value:'finish'});if(e.s.prompt?.type==='lifeTrigger')e.dispatch({type:'choose',value:'no'});assert.equal(e.list(1,'life').length,0);assert.equal(e.s.winner,null);});
test('counter has to exceed attacker; uses hand card and goes to trash',()=>{const e=game();e.s.players[0].turns=2;const c=give(e,'ST02-002','hand',1);e.dispatch({type:'attack',uid:e.list(0,'leader')[0].uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',uid:c.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(c.zone,'trash');assert.equal(e.list(1,'life').length,5);});
test('refresh returns attached DON and restores rested cards',()=>{const e=game(),l=e.list(0,'leader')[0];e.dispatch({type:'attach',uid:l.uid});l.rested=true;e.dispatch({type:'endTurn'});e.dispatch({type:'endTurn'});assert.equal(e.attached(l).length,0);assert.equal(l.rested,false);assert.equal(e.readyDon(0).length,3);});
test('undo restores exact state after legal operation',()=>{const e=game(),before=structuredClone(e.s);e.dispatch({type:'attach',uid:e.list(0,'leader')[0].uid});e.undo();assert.deepEqual(e.s,before);});
test('wrong color and unknown card decks are rejected',()=>{const e=game(),d=structuredClone(starter('ST01'));d.cards['ST02-004']=1;assert.ok(e.validateDeck(d).some(x=>x.includes('颜色')));d.cards['UNKNOWN']=1;assert.ok(e.validateDeck(d).some(x=>x.includes('未找到')));});
test('drawing the last card loses immediately, without waiting for next draw',()=>{const e=game();for(const c of e.list(1,'deck').slice(1))e.move(c,'trash');assert.equal(e.list(1,'deck').length,1);e.dispatch({type:'endTurn'});assert.equal(e.s.winner,0);assert.equal(e.list(1,'deck').length,0);});
test('top facedown life condition does not count facedown cards below a faceup top',()=>{const e=game(),l=e.list(0,'leader')[0];e.list(0,'life')[0].faceUp=true;assert.equal(e.conditions({FacedownLife:1},l),false);assert.equal(e.conditions({FaceupLife:1},l),true);});
test('an effect KO waits for a replacement cost before removing its target',()=>{const e=game();e.s.active=1;dons(e,1,4);const protectedCard=e.card('EB01-008',0,'field');e.mod(protectedCard,'power',-1000);const event=e.card('ST01-015',1,'hand'),cost=give(e,'ST01-014');e.dispatch({type:'play',uid:event.uid});e.dispatch({type:'choose',uids:[protectedCard.uid]});assert.equal(e.s.prompt.type,'replacement');assert.equal(protectedCard.zone,'field');e.dispatch({type:'choose',value:'yes'});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[cost.uid]});assert.equal(cost.zone,'trash');assert.equal(protectedCard.zone,'field');assert.equal(e.s.prompt,null);e.assertState();});
test('declining replacement lets the original KO finish',()=>{const e=game();e.s.active=1;dons(e,1,4);const c=e.card('EB01-008',0,'field');e.mod(c,'power',-1000);const event=e.card('ST01-015',1,'hand');e.dispatch({type:'play',uid:event.uid});e.dispatch({type:'choose',uids:[c.uid]});e.dispatch({type:'choose',value:'no'});assert.equal(c.zone,'trash');assert.equal(e.s.prompt,null);});
test('effect-only replacement is not offered for combat KO',()=>{const e=game();e.s.active=1;e.s.players[1].turns=2;const c=e.card('EB01-008',0,'field');c.rested=true;e.mod(c,'power',-3000);e.dispatch({type:'attack',uid:e.list(1,'leader')[0].uid,target:c.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(c.zone,'trash');assert.equal(e.s.prompt,null);});
test('Kaido requires seven chosen DON including active, rested and attached cards',()=>{const e=game(),l=e.list(0,'leader')[0];l.id='ST04-001';dons(e,0,10);const ds=e.don(0);ds[0].attached=l.uid;ds[1].rested=true;e.dispatch({type:'activate',uid:l.uid,index:0});assert.equal(e.s.prompt.min,7);assert.equal(e.s.prompt.max,7);assert.equal(e.s.prompt.candidates.length,10);const chosen=ds.slice(0,7).map(x=>x.uid);e.dispatch({type:'choose',uids:chosen});assert.equal(e.don(0).length,3);assert.ok(chosen.every(u=>e.s.cards[u].zone==='donReserve'));e.dispatch({type:'choose',value:'1'});assert.equal(e.list(1,'life').length,4);assert.equal(e.s.prompt,null);});
test('Kaido cannot activate with insufficient total DON',()=>{const e=game(),l=e.list(0,'leader')[0];l.id='ST04-001';assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}),/不足/);assert.equal(e.list(1,'life').length,5);});
test('mandatory on-play draw is automatic, not a skippable yes/no choice',()=>{const e=game();dons(e,0,4);const c=e.card('EB01-023',0,'hand'),n=e.list(0,'hand').length;e.dispatch({type:'play',uid:c.uid});assert.equal(e.s.prompt,null);assert.equal(e.list(0,'hand').length,n);assert.equal(c.zone,'field');});
test('DON selection shows all physical states and never requests an undefined image',()=>{const e=game(),l=e.list(0,'leader')[0];l.id='ST04-001';dons(e,0,10);const ds=e.don(0);ds[0].attached=l.uid;ds[1].rested=true;e.dispatch({type:'activate',uid:l.uid,index:0});const html=table(e,0,[ds[0].uid,ds[1].uid]);assert.equal((html.match(/class="don-face"/g)||[]).length,10);assert.ok(html.includes('附加于'));assert.ok(html.includes('selection-number">2'));assert.ok(!html.includes('src="undefined"'));});
test('unlimited-copy cards permit fifty copies while normal cards retain four-copy limit',()=>{const e=game();for(const id of ['OP01-075','OP08-072','OP16-042']){const leader=cards.find(c=>c.type==='领袖'&&e.db[id].colors.every(x=>c.colors.includes(x)));assert.deepEqual(e.validateDeck({cards:{[leader.id]:1,[id]:50}}),[])}assert.ok(e.validateDeck({cards:{'ST01-001':1,'ST01-003':50}}).some(x=>x.includes('1–4')));});
test('hand cost reduction applies only while its condition and hand zone hold',()=>{const e=game(),c=e.card('EB04-061',0,'hand'),base=e.def(c).cost;assert.equal(e.cost(c),base);for(const x of e.list(0,'life').slice(1))e.move(x,'trash');assert.equal(e.cost(c),base-1);e.move(c,'field');assert.equal(e.cost(c),base);e.move(c,'hand');e.move(e.list(0,'trash')[0],'life');assert.equal(e.cost(c),base);});
test('life-trigger deployment at a full field discards the chosen character without paying DON',()=>{const e=game();e.s.active=1;e.s.players[1].turns=2;const incoming=give(e,'ST01-002','life');for(let i=0;i<5;i++)e.card('ST01-003',0,'field');const old=e.list(0,'field')[0],don=e.don(0)[0];don.attached=old.uid;const life=e.list(0,'life').length;e.dispatch({type:'attack',uid:e.list(1,'leader')[0].uid,target:e.list(0,'leader')[0].uid});e.dispatch({type:'choose',value:'finish'});assert.equal(e.s.prompt.type,'lifeTrigger');e.dispatch({type:'choose',value:'yes'});assert.equal(e.s.prompt.type,'effectDeployReplace');assert.equal(e.s.prompt.candidates.length,5);e.dispatch({type:'choose',uids:[old.uid]});assert.equal(incoming.zone,'field');assert.equal(old.zone,'trash');assert.equal(e.list(0,'field').length,5);assert.equal(e.list(0,'life').length,life-1);assert.equal(don.attached,undefined);assert.ok(don.rested);assert.equal(e.don(0).length,1);assert.equal(e.s.prompt,null);e.assertState();});
