import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Engine} from '../dist/engine.mjs';
const read=n=>JSON.parse(readFileSync(new URL('../dist/data/'+n+'.json',import.meta.url)));
const cards=read('cards'),rules=read('rules'),decks=read('decks');
function game(){const e=new Engine(cards,rules,{seed:42});e.start(['ST01','ST02'].map(n=>decks.find(d=>d.name.startsWith(n))));e.dispatch({type:'choose',value:'keep'});e.dispatch({type:'choose',value:'keep'});return e;}
function don(e,n=10){for(const c of e.list(0,'donReserve').slice(0,n-e.don(0).length))e.move(c,'don');}

test('alternate target lets EB03 Otama rest an enemy DON without permitting friendly DON',()=>{const e=game();const source=e.card('EB03-012',0,'field');const enemy=e.list(1,'donReserve')[0];e.move(enemy,'don');e.dispatch({type:'activate',uid:source.uid,index:0});assert.ok(source.rested);assert.ok(e.s.prompt.candidates.includes(enemy.uid));assert.ok(!e.s.prompt.candidates.includes(e.don(0)[0].uid));e.dispatch({type:'choose',uids:[enemy.uid]});assert.equal(enemy.rested,true);});

test('ST10 Luffy gains DON at zero or eight, but not in between and not twice a turn',()=>{for(const n of [0,1,7,8]){const e=game(),l=e.list(0,'leader')[0];l.id='ST10-002';if(n===0)e.move(e.don(0)[0],'donReserve');else don(e,n);if(n===1||n===7)assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}),/条件/);else{e.dispatch({type:'activate',uid:l.uid,index:0});assert.equal(e.don(0).length,n+1);assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}));}}});

test('ST10 Zoro gains rush only when an opposing character reaches 5000 power; a leader alone does not qualify',()=>{for(const power of [0,4000,5000]){const e=game();don(e);e.s.players[0].turns=2;if(power){const enemy=e.card('ST02-004',1,'field');e.mod(enemy,'power',power-e.def(enemy).power);}const zoro=e.card('ST10-004',0,'hand');e.dispatch({type:'play',uid:zoro.uid});assert.equal(e.canAttack(zoro,e.list(1,'leader')[0]),power===5000);}});

test('ST12 Mihawk accepts a Slash character outside its category, but keeps cost/name/rested restrictions',()=>{const e=game();don(e);const mihawk=e.card('ST12-003',0,'hand'),zoro=e.card('ST01-013',0,'hand'),expensive=e.card('ST13-009',0,'hand');e.dispatch({type:'play',uid:mihawk.uid});assert.equal(e.s.prompt.type,'targets');assert.ok(e.s.prompt.candidates.includes(zoro.uid));assert.ok(!e.s.prompt.candidates.includes(expensive.uid));assert.ok(!e.s.prompt.candidates.includes(mihawk.uid));e.dispatch({type:'choose',uids:[zoro.uid]});assert.equal(zoro.zone,'field');assert.equal(zoro.rested,true);});

test('ST13 Dadan remembers all previous names across three deployments',()=>{const e=game();don(e);const source=e.card('ST13-006',0,'hand'),sabo=e.card('ST13-007',0,'hand'),duplicate=e.card('ST13-007',0,'hand'),ace=e.card('ST13-010',0,'hand'),luffy=e.card('ST13-014',0,'hand');e.dispatch({type:'play',uid:source.uid});e.dispatch({type:'choose',uids:[sabo.uid]});assert.ok(!e.s.prompt.candidates.includes(duplicate.uid));e.dispatch({type:'choose',uids:[ace.uid]});assert.ok(!e.s.prompt.candidates.includes(duplicate.uid));assert.ok(e.s.prompt.candidates.includes(luffy.uid));e.dispatch({type:'choose',uids:[luffy.uid]});assert.equal(e.list(0,'field').length,4);assert.equal(duplicate.zone,'hand');assert.equal(e.s.prompt,null);});

test('ST14 leader and stage cost buffs stack only for eligible field characters and update leader power',()=>{const e=game(),leader=e.list(0,'leader')[0];leader.id='ST14-001';const black=e.card('ST14-006',0,'field'),red=e.card('ST01-003',0,'field'),hand=e.card('ST14-008',0,'hand'),big=e.card('ST14-010',0,'field');const base=e.def(big).cost;e.mod(big,'cost',7-base);e.dispatch({type:'attach',uid:leader.uid});assert.equal(e.cost(black),4);assert.equal(e.cost(red),e.def(red).cost+1);assert.equal(e.cost(hand),1);assert.equal(e.power(leader),7000);const stage=e.card('ST14-017',0,'stage');assert.equal(e.cost(black),5);assert.equal(e.cost(red),e.def(red).cost+1);e.move(stage,'trash');assert.equal(e.cost(black),4);});

test('opponent field cost aura affects neither its own field nor either hand and expires when its source leaves',()=>{const e=game();const source=e.card('OP07-081',0,'field'),enemy=e.card('ST02-004',1,'field'),own=e.card('ST01-003',0,'field'),hand=e.card('ST02-004',1,'hand');e.dispatch({type:'attach',uid:source.uid});assert.equal(e.cost(enemy),e.def(enemy).cost-1);assert.equal(e.cost(own),e.def(own).cost);assert.equal(e.cost(hand),e.def(hand).cost);e.move(source,'trash');assert.equal(e.cost(enemy),e.def(enemy).cost);});

test('ST08 Uta resists the matching leader strike but remains vulnerable to a character attack',()=>{const e=game();e.s.players[0].turns=2;const uta=e.card('ST08-002',1,'field');uta.rested=true;e.dispatch({type:'attack',uid:e.list(0,'leader')[0].uid,target:uta.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(uta.zone,'field');const attacker=e.card('ST01-012',0,'field');e.dispatch({type:'attack',uid:attacker.uid,target:uta.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(uta.zone,'trash');});

test('ST10 Luffy reacts to an opposing blocker and KOing that blocker ends the battle without leader damage',()=>{const e=game();e.s.players[0].turns=2;const luffy=e.card('ST10-006',0,'field'),blocker=e.card('ST02-004',1,'field');e.dispatch({type:'attack',uid:luffy.uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',uids:[blocker.uid]});assert.equal(e.s.prompt.type,'targets');assert.equal(e.s.prompt.owner,0);e.dispatch({type:'choose',uids:[blocker.uid]});assert.equal(blocker.zone,'trash');assert.equal(e.list(1,'life').length,5);assert.equal(e.s.battle,null);assert.equal(luffy.used[1],e.s.turn);});

test('ST08 leader reacts to a real KO, but not merely discarding a character',()=>{const e=game(),leader=e.list(0,'leader')[0];leader.id='ST08-001';e.s.players[0].turns=2;const target=e.card('ST02-004',1,'field');target.rested=true;e.don(0)[0].rested=true;e.dispatch({type:'attack',uid:leader.uid,target:target.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[leader.uid]});assert.equal(e.attached(leader).length,1);const other=e.card('ST01-003',0,'field');e.move(other,'trash');e.pump();assert.equal(e.s.prompt,null);});

test('random discard from ST10 Law pays one DON and is deterministic after undo',()=>{const e=game();don(e);while(e.list(1,'hand').length<7)e.card('ST02-002',1,'hand');const law=e.card('ST10-010',0,'hand');e.dispatch({type:'play',uid:law.uid});e.dispatch({type:'choose',value:'yes'});const chosen=e.don(0)[0].uid;e.dispatch({type:'choose',uids:[chosen]});const trashed=e.s.players[1].trash.slice();assert.equal(trashed.length,2);assert.equal(e.list(1,'hand').length,5);assert.equal(e.don(0).length,9);e.undo();e.dispatch({type:'choose',uids:[chosen]});assert.deepEqual(e.s.players[1].trash,trashed);});

test('deck search prefilters its pool and does not ask a redundant first selection',()=>{const e=game();don(e);const source=e.card('ST03-007',0,'field'),pacifista=e.card('ST03-012',0,'deck');e.dispatch({type:'attach',uid:source.uid});e.dispatch({type:'activate',uid:source.uid,index:0});assert.equal(e.s.prompt.type,'targets');assert.ok(e.s.prompt.candidates.includes(pacifista.uid));assert.ok(e.s.prompt.task.revealed.uids.every(u=>e.rule(e.s.cards[u]).characterName==='Pacifista'));e.dispatch({type:'choose',uids:[pacifista.uid]});assert.equal(pacifista.zone,'field');assert.equal(e.s.prompt,null);});

test('EB01 Viola can reorder the opponent life stack after choosing the arrange branch',()=>{const e=game();don(e);const viola=e.card('EB01-052',0,'hand');const before=e.list(1,'life').map(c=>c.uid);e.dispatch({type:'play',uid:viola.uid});e.dispatch({type:'choose',value:'0'});assert.equal(e.s.prompt.type,'order');e.dispatch({type:'choose',uids:before.slice().reverse()});assert.deepEqual(e.list(1,'life').map(c=>c.uid),before.slice().reverse());});

test('shared migration templates transfer DON, copy power, deal damage and activate DON at end turn',()=>{const e=game(),source=e.card('EB02-009',0,'stage'),from=e.card('ST01-003',0,'field'),to=e.card('ST01-004',0,'field'),enemy=e.card('ST02-004',1,'field');e.move(e.list(0,'donReserve')[0],'don');e.dispatch({type:'attach',uid:from.uid});const attached=e.attached(from)[0];e.applyEffects({TransferDon:true},source,[attached,to],{});assert.equal(attached.attached,to.uid);e.applyEffects({MatchOpponentPowerUntilTurnEnd:true},source,[enemy],{});assert.equal(e.power(source),e.power(enemy));const life=e.card('ST02-002',1,'life'),lifeBefore=e.list(1,'life').length;e.applyEffects({DealDamage:true},source,[],{});e.pump();assert.equal(e.list(1,'life').length,lifeBefore-1);const ready=e.readyDon(0)[0];ready.rested=true;e.applyEffects({TurnEndActivateDon:1},source,[],{});e.dispatch({type:'endTurn'});assert.equal(ready.rested,false);});

test('shared target-count, second-cost and field power templates apply their dynamic values',()=>{const e=game(),source=e.card('ST01-003',0,'field'),first=e.card('ST02-004',1,'field'),second=e.card('ST02-003',1,'field'),high=e.card('ST02-014',1,'field');assert.equal(e.matches(second,{DeployedCharacter:true,EnemyOnly:true,SecondCostOrLess:2},source,{selected:[first.uid]}),true);assert.equal(e.matches(high,{DeployedCharacter:true,EnemyOnly:true,SecondCostOrLess:2},source,{selected:[first.uid]}),false);const target={OverrideUITargetCount:2,TargetCount:1};assert.equal(target.OverrideUITargetCount,2);const aura=e.card('EB04-003',0,'field'),navy=e.list(0,'leader')[0];navy.id='ST06-001';e.s.active=1;assert.equal(e.power(navy),7000);e.applyEffects({BuffCombatPower:2000},source,[source],{});assert.equal(e.power(source),5000);});

test('power, opponent-life cost and rested-category conditions filter effects correctly',()=>{const e=game(),source=e.card('OP14-002',0,'field'),enemy=e.card('ST02-014',1,'field');assert.equal(e.conditions({PowerXOrMore:5000},source),false);e.mod(source,'power',3000);assert.equal(e.conditions({PowerXOrMore:5000},source),true);assert.equal(e.matches(enemy,{DeployedCharacter:true,EnemyOnly:true,CostOppLifeOrLess:true},source),true);for(const life of e.list(1,'life').slice(2))e.move(life,'trash');assert.equal(e.matches(enemy,{DeployedCharacter:true,EnemyOnly:true,CostOppLifeOrLess:true},source),false);const odyssey=e.card('OP10-033',0,'field'),other=e.card('OP10-033',0,'field');odyssey.rested=true;other.rested=true;assert.equal(e.conditions({SelfRestedCharacterCategory:{eCategory:'ODYSSEY',iCount:2}},source),true);});

test('opponent board, DON-cost and previous-target templates use live board state',()=>{const e=game(),source=e.card('ST01-003',0,'field'),enemy=e.card('ST02-014',1,'field');assert.equal(e.conditions({OppCharPowerXOrMore:5000},source),true);e.move(enemy,'trash');assert.equal(e.conditions({OppCharPowerXOrMore:5000},source),false);const high=e.card('ST02-014',1,'field'),second=e.card('ST02-003',1,'field');assert.equal(e.conditions({OppNo2CharsBaseXOrMore:5000},source),true);e.card('ST02-014',1,'field');assert.equal(e.conditions({OppNo2CharsBaseXOrMore:5000},source),false);e.move(e.list(0,'donReserve')[0],'don');assert.equal(e.matches(second,{HandCard:true,FriendlyOnly:true,CostDonOrLess:true},source,{}),false);const hand=e.card('ST01-015',0,'hand');assert.equal(e.matches(hand,{HandCard:true,FriendlyOnly:true,CostDonOrLess:true},source,{}),false);e.move(e.list(0,'donReserve')[0],'don');e.move(e.list(0,'donReserve')[0],'don');assert.equal(e.matches(hand,{HandCard:true,FriendlyOnly:true,CostDonOrLess:true},source,{}),true);e.applyEffects({BuffPower:1000},source,[source],{});assert.equal(e.power(source),4000);});

test('rest, category companion, attached DON and optional return templates use current state',()=>{const e=game(),rest=e.card('OP14-027',0,'field'),enemy=e.card('ST02-014',1,'field');rest.rested=true;e.emit('OnRest',rest,{owner:0});e.pump();assert.equal(e.s.prompt.type,'targets');assert.ok(e.s.prompt.candidates.includes(enemy.uid));e.s.prompt=null;const ally=e.card('OP06-113',0,'field'),companion=e.card('OP08-098',0,'field');e.rule(companion).cardCategories=['ShandoraWarrior'];assert.equal(e.conditions({AnotherCharacterOfCategory:['ShandoraWarrior']},ally),true);e.move(e.list(1,'donReserve')[0],'don');const enemyDon=e.list(1,'don')[0];enemyDon.attached=enemy.uid;assert.equal(e.matches(enemy,{DeployedCharacter:true,EnemyOnly:true,GivenDon:1},rest,{}),true);e.move(e.list(0,'donReserve')[0],'don');const ownDon=e.readyDon(0)[0];ownDon.attached=rest.uid;e.applyEffects({OptionalReturnDon:true},rest,[ownDon],{});assert.equal(ownDon.zone,'donReserve');});

test('zero-power and trash-count templates use live values',()=>{const e=game(),source=e.card('ST01-003',0,'field'),target=e.card('ST02-014',1,'field'),leader=e.list(0,'leader')[0];const baseTargetPower=e.def(target).power;e.applyEffects({SetPowerToZero:true},source,[target],{});assert.equal(e.power(target),0);e.applyEffects({SetBasePowerToZero:true},source,[source],{});assert.equal(e.power(source),0);assert.equal(e.conditions({LeaderPowerZero:true},leader),false);e.mod(leader,'basePower',0);assert.equal(e.conditions({LeaderPowerZero:true},leader),true);const trashPower=e.card('EB04-048',0,'field'),costPower=e.card('EB04-048',0,'hand');e.rules['EB04-048']={actionV3s:[{proc:{Passive:true},steps:[{effect:{Passive1KPerXTrash:5,Passive2CostPerXTrash:5}}]}]};for(let i=0;i<5;i++)e.card('ST01-003',0,'trash');assert.equal(e.power(trashPower),e.def(trashPower).power+1000);assert.equal(e.cost(costPower),Math.max(0,e.def(costPower).cost-2));const eventPower=e.card('EB01-027',0,'field');e.rules['EB01-027']={actionV3s:[{proc:{Passive:true},steps:[{effect:{Passive1KPerXEventTrash:2}}]}]};for(let i=0;i<2;i++)e.card('ST01-015',0,'trash');assert.equal(e.power(eventPower),e.def(eventPower).power+1000);const donPower=e.card('EB01-014',0,'field');e.rules['EB01-014']={actionV3s:[{proc:{Passive:true},steps:[{effect:{Passive1KPerXRestedDon:3}}]}]};for(let i=0;i<3;i++){const d=e.list(0,'donReserve')[0];e.move(d,'don');d.rested=true}assert.equal(e.power(donPower),e.def(donPower).power+1000);e.dispatch({type:'endTurn'});assert.equal(e.power(target),baseTargetPower);});

test('field double attack and defender replacement templates affect combat',()=>{const e=game(),attacker=e.list(0,'leader')[0],defender=e.list(1,'leader')[0],replacement=e.card('ST02-003',1,'field');e.rules[attacker.id]={actionV3s:[{proc:{Passive:true},steps:[{effect:{FieldDoubleAttack:true}}]}]};assert.equal(e.flags(attacker).DoubleAttack,true);e.s.battle={attacker:attacker.uid,target:defender.uid,defender:1,counter:0,blocked:false};e.applyEffects({BecomeDefenderCharacter:true},replacement,[replacement],{});assert.equal(e.s.battle.target,replacement.uid);assert.equal(e.s.battle.blocked,true);});

test('life damage shield prevents damage until its owner starts a turn',()=>{const e=game(),source=e.list(0,'leader')[0];for(const x of e.list(0,'life').slice())e.move(x,'trash');e.card('ST01-003',0,'life');const before=e.list(0,'life').length;e.applyEffects({NoTakeLifeToTurnStart:true},source,[],{});e.task({kind:'damage',owner:0});assert.equal(e.list(0,'life').length,before);e.task({kind:'beginTurn'});e.task({kind:'damage',owner:0});assert.equal(e.list(0,'life').length,before-1);});

test('DON activation lock blocks effect activation until the turn ends',()=>{const e=game(),source=e.list(0,'leader')[0],don=e.don(0)[0];don.rested=true;e.applyEffects({CantActivateDonToTurnEnd:true},source,[],{});e.applyEffects({Activate:true},source,[don],{});assert.equal(don.rested,true);e.task({kind:'finishTurn'});e.applyEffects({Activate:true},source,[don],{});assert.equal(don.rested,false);});

test('field noncombat KO immunity protects matching allies only',()=>{const e=game(),aura=e.card('OP07-069',0,'field'),ally=e.card('ST01-003',0,'field'),other=e.card('ST02-003',1,'field');e.rules[aura.id]={actionV3s:[{proc:{Passive:true},steps:[{target:[{DeployedCharacter:true,FriendlyOnly:true,OnlySelf:false,OnlyNames:[e.rule(ally).characterName]}],effect:{OtherCharsImmuneToNoncombatKO:true}}]}]};assert.equal(e.flags(ally).ImmuneToNoncombat,true);e.remove(ally,'trash',false,aura);e.pump();assert.equal(ally.zone,'field');e.remove(other,'trash',false,aura);e.pump();assert.equal(other.zone,'trash');});

test('combined life and opposing DON limits filter effect targets',()=>{const e=game(),source=e.card('ST01-003',0,'field'),low=e.card('ST02-003',1,'field'),high=e.card('ST02-014',1,'field');assert.equal(e.matches(low,{DeployedCharacter:true,EnemyOnly:true,CostCombinedLifeOrLess:true},source,{}),true);for(const x of e.list(0,'life').slice(1))e.move(x,'trash');for(const x of e.list(1,'life').slice(1))e.move(x,'trash');assert.equal(e.matches(high,{DeployedCharacter:true,EnemyOnly:true,CostCombinedLifeOrLess:true},source,{}),false);const hand=e.card('ST01-015',0,'hand');assert.equal(e.matches(hand,{HandCard:true,FriendlyOnly:true,CostOppDonOrLess:true},source,{}),false);for(let i=0;i<e.def(hand).cost;i++)e.move(e.list(1,'donReserve')[0],'don');assert.equal(e.matches(hand,{HandCard:true,FriendlyOnly:true,CostOppDonOrLess:true},source,{}),true);});

test('trash-life-to retains exactly the requested number of life cards',()=>{const e=game(),source=e.list(0,'leader')[0],beforeTrash=e.list(0,'trash').length;e.applyEffects({TrashLifeTo:1},source,[],{});assert.equal(e.list(0,'life').length,1);assert.equal(e.list(0,'trash').length,beforeTrash+4);e.applyEffects({TrashLifeTo:1},source,[],{});assert.equal(e.list(0,'life').length,1);});

test('rest and combat immunity templates honor their duration',()=>{const e=game(),source=e.list(0,'leader')[0],target=e.card('ST01-003',0,'field');e.rules[target.id]={actionV3s:[{proc:{Passive:true},steps:[{effect:{ImmuneToRest:true}}]}]};e.applyEffects({Rest:true},source,[target],{});assert.equal(target.rested,false);e.applyEffects({GainCombatImmuneToStart:true},source,[target],{});assert.equal(e.flags(target).ImmuneToBattle,true);target.mods=[];e.applyEffects({GainCombatImmuneToStart:true},source,[target],{});e.s.active=1;e.task({kind:'beginTurn'});e.s.active=0;e.task({kind:'beginTurn'});assert.equal(e.flags(target).ImmuneToBattle,undefined);});

test('base power swaps exchange current base values',()=>{const e=game(),source=e.list(0,'leader')[0],a=e.card('ST01-003',0,'field'),b=e.card('ST01-004',0,'field');const [ap,bp]=[e.basePower(a),e.basePower(b)];e.applyEffects({SwapBasePower:true},source,[a,b],{});assert.equal(e.basePower(a),bp);assert.equal(e.basePower(b),ap);const leader=e.list(0,'leader')[0],lp=e.basePower(leader),xp=e.basePower(a);e.applyEffects({SwapBasePowerWithLeader:true},source,[a],{});assert.equal(e.basePower(leader),xp);assert.equal(e.basePower(a),lp);});

test('saved counts and hand overflow calculate later effects',()=>{const e=game(),source=e.list(0,'leader')[0],t={};while(e.list(0,'hand').length<7)e.card('ST01-003',0,'hand');assert.equal(Math.max(0,e.list(0,'hand').length-5),2);e.applyEffects({SaveTargetCount:true},source,[source,e.list(0,'hand')[0]],t);const before=e.list(0,'hand').length;e.applyEffects({DrawSavedCount:true},source,[],t);assert.equal(e.list(0,'hand').length,before+2);const h={};e.applyEffects({SaveHandSize:true},source,[],h);assert.equal(h.savedHandSize,e.list(0,'hand').length);});

test('leader base-power matching templates track the leader',()=>{const e=game(),leader=e.list(0,'leader')[0],source=e.card('OP14-053',0,'field');e.mod(leader,'basePower',7000);e.rules[source.id]={actionV3s:[{proc:{Passive:true},steps:[{effect:{PassiveBasePowerMatchLeader:true}}]}]};assert.equal(e.power(source),7000);const target=e.card('ST01-003',0,'field');e.applyEffects({MatchLeaderToBasePowerUntilTurnEnd:true},source,[target],{});assert.equal(e.basePower(target),7000);});
