import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Engine} from '../dist/engine.mjs';
const read=n=>JSON.parse(readFileSync(new URL('../dist/data/'+n+'.json',import.meta.url)));
const cards=read('cards'),rules=read('rules'),decks=read('decks');
function game(){const e=new Engine(cards,rules,{seed:42});e.start(['ST01','ST02'].map(n=>decks.find(d=>d.name.startsWith(n))));e.dispatch({type:'choose',value:'keep'});e.dispatch({type:'choose',value:'keep'});return e;}
function don(e,n=10){for(const c of e.list(0,'donReserve').slice(0,n-e.don(0).length))e.move(c,'don');}

test('alternate target lets EB03 Otama rest an enemy DON without permitting friendly DON',()=>{const e=game();const source=e.card('EB03-012',0,'field');const enemy=e.list(1,'donReserve')[0];e.move(enemy,'don');e.dispatch({type:'activate',uid:source.uid,index:0});assert.ok(source.rested);assert.ok(e.s.prompt.candidates.includes(enemy.uid));assert.ok(!e.s.prompt.candidates.includes(e.don(0)[0].uid));e.dispatch({type:'choose',uids:[enemy.uid]});assert.equal(enemy.rested,true);});

test('ST10 Luffy gains DON at zero or eight, but not in between and not twice a turn',()=>{for(const n of [0,1,7,8]){const e=game(),l=e.list(0,'leader')[0];l.id='ST10-002';if(n===0)e.move(e.don(0)[0],'donReserve');else don(e,n);if(n===1||n===7)assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}),/条件/);else{e.dispatch({type:'activate',uid:l.uid,index:0});assert.equal(e.don(0).length,n+1);assert.throws(()=>e.dispatch({type:'activate',uid:l.uid,index:0}));}}});

test('ST10 Zoro gains rush only when an opposing character reaches 5000 power; a leader alone does not qualify',()=>{for(const power of [0,4000,5000]){const e=game();don(e);e.s.players[0].turns=2;if(power){const enemy=e.card('ST02-004',1,'field');e.mod(enemy,'power',power-e.def(enemy).power);}const zoro=e.card('ST10-004',0,'hand');e.dispatch({type:'play',uid:zoro.uid});assert.equal(e.canAttack(zoro,e.list(1,'leader')[0]),power===5000);}});

test('ST12 Mihawk accepts a Slash character outside its category, but keeps cost/name/rested restrictions',()=>{const e=game();don(e);const mihawk=e.card('ST12-003',0,'hand'),zoro=e.card('ST01-013',0,'hand'),expensive=e.card('ST13-009',0,'hand');e.dispatch({type:'play',uid:mihawk.uid});assert.equal(e.s.prompt.type,'targets');assert.ok(e.s.prompt.candidates.includes(zoro.uid));assert.ok(!e.s.prompt.candidates.includes(expensive.uid));assert.ok(!e.s.prompt.candidates.includes(mihawk.uid));e.dispatch({type:'choose',uids:[zoro.uid]});assert.equal(zoro.zone,'field');assert.equal(zoro.rested,true);});

test('ST13 Dadan remembers all previous names across three deployments',()=>{const e=game();don(e);const source=e.card('ST13-006',0,'hand'),sabo=e.card('ST13-007',0,'hand'),duplicate=e.card('ST13-007',0,'hand'),ace=e.card('ST13-010',0,'hand'),luffy=e.card('ST13-014',0,'hand');e.dispatch({type:'play',uid:source.uid});e.dispatch({type:'choose',uids:[sabo.uid]});assert.ok(!e.s.prompt.candidates.includes(duplicate.uid));e.dispatch({type:'choose',uids:[ace.uid]});assert.ok(!e.s.prompt.candidates.includes(duplicate.uid));assert.ok(e.s.prompt.candidates.includes(luffy.uid));e.dispatch({type:'choose',uids:[luffy.uid]});assert.equal(e.list(0,'field').length,4);assert.equal(duplicate.zone,'hand');assert.equal(e.s.prompt,null);});

test('ST14 leader and stage cost buffs stack only for eligible field characters and update leader power',()=>{const e=game(),leader=e.list(0,'leader')[0];leader.id='ST14-001';const black=e.card('ST14-006',0,'field'),red=e.card('ST01-003',0,'field'),hand=e.card('ST14-008',0,'hand'),big=e.card('ST14-010',0,'field');const base=e.def(big).cost;e.mod(big,'cost',7-base);e.dispatch({type:'attach',uid:leader.uid});assert.equal(e.cost(black),4);assert.equal(e.cost(red),e.def(red).cost+1);assert.equal(e.cost(hand),1);assert.equal(e.power(leader),7000);const stage=e.card('ST14-017',0,'stage');assert.equal(e.cost(black),5);assert.equal(e.cost(red),e.def(red).cost+1);e.move(stage,'trash');assert.equal(e.cost(black),4);});

test('opponent field cost aura affects neither its own field nor either hand and expires when its source leaves',()=>{const e=game();const source=e.card('OP07-081',0,'field'),enemy=e.card('ST02-004',1,'field'),own=e.card('ST01-003',0,'field'),hand=e.card('ST02-004',1,'hand');e.dispatch({type:'attach',uid:source.uid});assert.equal(e.cost(enemy),e.def(enemy).cost-1);assert.equal(e.cost(own),e.def(own).cost);assert.equal(e.cost(hand),e.def(hand).cost);e.move(source,'trash');assert.equal(e.cost(enemy),e.def(enemy).cost);});

test('ST08 Uta resists the matching leader strike but remains vulnerable to a character attack',()=>{const e=game();e.s.players[0].turns=2;const uta=e.card('ST08-002',1,'field');uta.rested=true;e.dispatch({type:'attack',uid:e.list(0,'leader')[0].uid,target:uta.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(uta.zone,'field');const attacker=e.card('ST01-012',0,'field');e.dispatch({type:'attack',uid:attacker.uid,target:uta.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(uta.zone,'trash');});

test('ST10 Luffy reacts to an opposing blocker and KOing that blocker ends the battle without leader damage',()=>{const e=game();e.s.players[0].turns=2;const luffy=e.card('ST10-006',0,'field'),blocker=e.card('ST02-004',1,'field');e.dispatch({type:'attack',uid:luffy.uid,target:e.list(1,'leader')[0].uid});e.dispatch({type:'choose',uids:[blocker.uid]});assert.equal(e.s.prompt.type,'targets');assert.equal(e.s.prompt.owner,0);e.dispatch({type:'choose',uids:[blocker.uid]});assert.equal(blocker.zone,'trash');assert.equal(e.list(1,'life').length,5);assert.equal(e.s.battle,null);assert.equal(luffy.used[1],e.s.turn);});

test('ST08 leader reacts to a real KO, but not merely discarding a character',()=>{const e=game(),leader=e.list(0,'leader')[0];leader.id='ST08-001';e.s.players[0].turns=2;const target=e.card('ST02-004',1,'field');target.rested=true;e.don(0)[0].rested=true;e.dispatch({type:'attack',uid:leader.uid,target:target.uid});e.dispatch({type:'choose',value:'finish'});assert.equal(e.s.prompt.type,'targets');e.dispatch({type:'choose',uids:[leader.uid]});assert.equal(e.attached(leader).length,1);const other=e.card('ST01-003',0,'field');e.move(other,'trash');e.pump();assert.equal(e.s.prompt,null);});

test('random discard from ST10 Law pays one DON and is deterministic after undo',()=>{const e=game();don(e);while(e.list(1,'hand').length<7)e.card('ST02-002',1,'hand');const law=e.card('ST10-010',0,'hand');e.dispatch({type:'play',uid:law.uid});e.dispatch({type:'choose',value:'yes'});const chosen=e.don(0)[0].uid;e.dispatch({type:'choose',uids:[chosen]});const trashed=e.s.players[1].trash.slice();assert.equal(trashed.length,2);assert.equal(e.list(1,'hand').length,5);assert.equal(e.don(0).length,9);e.undo();e.dispatch({type:'choose',uids:[chosen]});assert.deepEqual(e.s.players[1].trash,trashed);});

test('deck search prefilters its pool and does not ask a redundant first selection',()=>{const e=game();don(e);const source=e.card('ST03-007',0,'field'),pacifista=e.card('ST03-012',0,'deck');e.dispatch({type:'attach',uid:source.uid});e.dispatch({type:'activate',uid:source.uid,index:0});assert.equal(e.s.prompt.type,'targets');assert.ok(e.s.prompt.candidates.includes(pacifista.uid));assert.ok(e.s.prompt.task.revealed.uids.every(u=>e.rule(e.s.cards[u]).characterName==='Pacifista'));e.dispatch({type:'choose',uids:[pacifista.uid]});assert.equal(pacifista.zone,'field');assert.equal(e.s.prompt,null);});

test('EB01 Viola can reorder the opponent life stack after choosing the arrange branch',()=>{const e=game();don(e);const viola=e.card('EB01-052',0,'hand');const before=e.list(1,'life').map(c=>c.uid);e.dispatch({type:'play',uid:viola.uid});e.dispatch({type:'choose',value:'0'});assert.equal(e.s.prompt.type,'order');e.dispatch({type:'choose',uids:before.slice().reverse()});assert.deepEqual(e.list(1,'life').map(c=>c.uid),before.slice().reverse());});

test('shared migration templates transfer DON, copy power, deal damage and activate DON at end turn',()=>{const e=game(),source=e.card('EB02-009',0,'stage'),from=e.card('ST01-003',0,'field'),to=e.card('ST01-004',0,'field'),enemy=e.card('ST02-004',1,'field');e.move(e.list(0,'donReserve')[0],'don');e.dispatch({type:'attach',uid:from.uid});const attached=e.attached(from)[0];e.applyEffects({TransferDon:true},source,[attached,to],{});assert.equal(attached.attached,to.uid);e.applyEffects({MatchOpponentPowerUntilTurnEnd:true},source,[enemy],{});assert.equal(e.power(source),e.power(enemy));const life=e.card('ST02-002',1,'life'),lifeBefore=e.list(1,'life').length;e.applyEffects({DealDamage:true},source,[],{});e.pump();assert.equal(e.list(1,'life').length,lifeBefore-1);const ready=e.readyDon(0)[0];ready.rested=true;e.applyEffects({TurnEndActivateDon:1},source,[],{});e.dispatch({type:'endTurn'});assert.equal(ready.rested,false);});

test('shared target-count, second-cost and field power templates apply their dynamic values',()=>{const e=game(),source=e.card('ST01-003',0,'field'),first=e.card('ST02-004',1,'field'),second=e.card('ST02-003',1,'field'),high=e.card('ST02-014',1,'field');assert.equal(e.matches(second,{DeployedCharacter:true,EnemyOnly:true,SecondCostOrLess:2},source,{selected:[first.uid]}),true);assert.equal(e.matches(high,{DeployedCharacter:true,EnemyOnly:true,SecondCostOrLess:2},source,{selected:[first.uid]}),false);const target={OverrideUITargetCount:2,TargetCount:1};assert.equal(target.OverrideUITargetCount,2);const aura=e.card('EB04-003',0,'field'),navy=e.list(0,'leader')[0];navy.id='ST06-001';e.s.active=1;assert.equal(e.power(navy),7000);e.applyEffects({BuffCombatPower:2000},source,[source],{});assert.equal(e.power(source),5000);});
